#ifndef SDK_CONFIG_H
#define SDK_CONFIG_H

#define NRF_LOG_ENABLED 1
#define NRF_LOG_BACKEND_USB_ENABLED 1
#define NRF_LOG_DEFAULT_LEVEL 3

#define USBD_ENABLED 1
#define APP_USBD_ENABLED 1
#define APP_USBD_CDC_ACM_ENABLED 1
#define USBD_CONFIG_EVENT_QUEUE_ENABLE 1

#define NRF_DRV_CLOCK_ENABLED 1
#define APP_TIMER_ENABLED 1
#define APP_FIFO_ENABLED 1

#endif // SDK_CONFIG_H
